version: '3.3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "8889:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=empleados
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass1234
    volumes:
      - ./mysql_data:/var/lib/mysql:rw
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #image: php:7.4-apache
    #container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql